dummy

diff --git a/.github/workflows/cicd.yaml b/.github/workflows/cicd.yaml
--- a/.github/workflows/cicd.yaml
+++ b/.github/workflows/cicd.yaml
@@ -26,8 +26,19 @@ jobs:
           run: echo "Deploying to staging"
 
         - name: notify main is green [main/base branch]
+          env:
+            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           run: |
-            gh pr list --state open --json number | jq -r '.[].number' | while read pr; do
-            gh workflow run cicd.yaml --ref refs/pull/$pr/head
-            done
-            echo "Triggered workflow on all open PRs"
+            main_workflow_status=$(gh run list --branch main --workflow cicd.yaml --json status --jq '.[0].status')
+            if [ "$main_workflow_status" != "completed" ]; then
+              echo "Main branch workflow is not completed. Failing the step."
+              exit 1
+            fi
+            if [ "$(gh run view --branch main --workflow cicd.yaml --json conclusion --jq '.conclusion')" != "success" ]; then
+              echo "Main branch workflow failed. Failing the step."
+              exit 1
+            fi
+            # gh pr list --state open --json number | jq -r '.[].number' | while read pr; do
+            #   gh workflow run cicd.yaml --ref refs/pull/$pr/head
+            # done
+            # echo "Triggered workflow on all open PRs"
